import math
import random
import matplotlib.pyplot as plt

seed = random.randint(1, 10000)
numbers = []
for i in range(1000):
    seed = math.tan(seed)
    numbers.append(seed)

plt.hist(numbers)
plt.show()

# From the following graph we can see that using trigonometric functions and the PRNG generated by the
# programming language isn't actually random, we can see that the density of the numbers generated fall
# from -20 to 20 predominantly. Hence, using such a predictable PRNG is not suitable for cryptology.

